<?php

	$_LANG["softname"] = "Seabig 客户管理系统";
	$_LANG["colors"] = array(1=>array("color"=>"5d762a","name"=>"军绿色"),
	                         2=>array("color"=>"1eddff","name"=>"天蓝色"),
	                         3=>array("color"=>"d2691e","name"=>"巧克力色"),
	                         4=>array("color"=>"ffa500","name"=>"桔色"),
	                         5=>array("color"=>"98fb98","name"=>"浅绿色"),
	                         6=>array("color"=>"ffffb1","name"=>"浅黄色"),
	                         7=>array("color"=>"bdb76b","name"=>"深卡其布色"),
	                         8=>array("color"=>"666666","name"=>"深灰色"),
	                         9=>array("color"=>"4b0082","name"=>"深紫色"),
	                         10=>array("color"=>"ffffff","name"=>"白色"),
	                         11=>array("color"=>"ffb6c1","name"=>"粉红色"),
	                         12=>array("color"=>"dda0dd","name"=>"紫罗兰"),
	                         13=>array("color"=>"800080","name"=>"紫色"),
	                         14=>array("color"=>"ff0000","name"=>"红色"),
	                         15=>array("color"=>"008000","name"=>"绿色"),
	                         16=>array("color"=>"assortment","name"=>"花色"),
	                         17=>array("color"=>"0000ff","name"=>"蓝色"),
	                         18=>array("color"=>"855b00","name"=>"褐色"),
	                         19=>array("color"=>"transparent","name"=>"透明"),
	                         20=>array("color"=>"990000","name"=>"酒红色"),
	                         21=>array("color"=>"ffff00","name"=>"黄色"),
	                         22=>array("color"=>"000000","name"=>"黑色"));
	                         
   $_LANG["sizes"] = array(1=>array("size"=>"1","name"=>"11"),
	                         2=>array("size"=>"2","name"=>"12"),
	                         3=>array("size"=>"3","name"=>"13"),
	                         4=>array("size"=>"4","name"=>"14"),
	                         5=>array("size"=>"5","name"=>"15"),
	                         6=>array("size"=>"6","name"=>"16"),
	                         7=>array("size"=>"7","name"=>"17"),
	                         8=>array("size"=>"8","name"=>"18"),
	                         9=>array("size"=>"9","name"=>"19"),
	                         10=>array("size"=>"10","name"=>"20"),
	                         11=>array("size"=>"11","name"=>"21"),
	                         12=>array("size"=>"12","name"=>"22"),
	                         13=>array("size"=>"13","name"=>"23"),
	                         14=>array("size"=>"14","name"=>"24"),
	                         15=>array("size"=>"15","name"=>"25"),
	                         16=>array("size"=>"16","name"=>"26"),
	                         17=>array("size"=>"17","name"=>"27"),
	                         18=>array("size"=>"18","name"=>"28"),
	                         19=>array("size"=>"19","name"=>"29"),
	                         20=>array("size"=>"10","name"=>"S"),
	                         21=>array("size"=>"21","name"=>"M"),
	                         22=>array("size"=>"22","name"=>"L"),
	                         23=>array("size"=>"23","name"=>"XL"),
	                         24=>array("size"=>"24","name"=>"XXL"),
	                         25=>array("size"=>"25","name"=>"XXXL"));
?>